export default {
  content: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.ts',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-variant': '#dae2fd',
        'surface-bright': '#faf8ff',
        'on-secondary': '#ffffff',
        outline: '#936e6d',
        'tertiary-fixed-dim': '#75d1ff',
        tertiary: '#006384',
        'secondary-fixed-dim': '#d4bbff',
        'secondary-fixed': '#ebdcff',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'surface-dim': '#d2d9f4',
        'inverse-surface': '#283044',
        'inverse-primary': '#ffb3b2',
        'on-surface': '#131b2e',
        'on-secondary-fixed': '#270058',
        error: '#ba1a1a',
        'secondary-container': '#731be5',
        'primary-container': '#e90038',
        'surface-container-high': '#e2e7ff',
        background: '#faf8ff',
        'surface-container-low': '#f2f3ff',
        surface: '#faf8ff',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed-variant': '#92001f',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#004d67',
        'surface-container': '#eaedff',
        'on-secondary-container': '#fdf6ff',
        'surface-tint': '#bf002c',
        'outline-variant': '#e8bcbb',
        'tertiary-fixed': '#c2e8ff',
        'tertiary-container': '#007ea6',
        'on-surface-variant': '#5e3f3e',
        'on-secondary-fixed-variant': '#5d00c2',
        'surface-container-highest': '#dae2fd',
        secondary: '#731be5',
        'on-primary-fixed': '#410008',
        'on-tertiary-fixed': '#001e2b',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#ffdad9',
        primary: '#ba002b',
        'on-error': '#ffffff',
        'on-tertiary-container': '#fbfcff',
        'primary-fixed-dim': '#ffb3b2',
        'on-background': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-desktop': '40px',
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-md': ['Sora'],
        display: ['Sora'],
        'label-md': ['Sora'],
        'body-lg': ['Sora'],
        'label-sm': ['Sora'],
        'headline-lg': ['Sora'],
        'headline-lg-mobile': ['Sora'],
        'headline-md': ['Sora'],
      },
      fontSize: {
        'body-md': ['16px', {
          lineHeight: '1.6',
          fontWeight: '400',
        }],
        display: ['48px', {
          lineHeight: '1.1',
          letterSpacing: '-0.02em',
          fontWeight: '700',
        }],
        'label-md': ['14px', {
          lineHeight: '1.4',
          letterSpacing: '0.05em',
          fontWeight: '600',
        }],
        'body-lg': ['18px', {
          lineHeight: '1.6',
          fontWeight: '400',
        }],
        'label-sm': ['12px', {
          lineHeight: '1.4',
          letterSpacing: '0.02em',
          fontWeight: '500',
        }],
        'headline-lg': ['32px', {
          lineHeight: '1.2',
          letterSpacing: '-0.01em',
          fontWeight: '600',
        }],
        'headline-lg-mobile': ['28px', {
          lineHeight: '1.2',
          fontWeight: '600',
        }],
        'headline-md': ['24px', {
          lineHeight: '1.3',
          fontWeight: '600',
        }],
      },
    },
  },
};
